# 文件与文件夹相关操作



## 1 flie对象常用的函数


file 对象使用 open 函数来创建，下面列出了 file 对象的常用的函数，并对其功能进行了介绍： 


1 
file.close()

关闭文件。关闭后文件不能再进行读写操作。
 
2 
file.flush()

刷新文件内部缓冲，直接把内部缓冲区的数据立刻写入文件, 而不是被动的等待输出缓冲区写入。
 
3 
file.fileno()

返回一个整型的文件描述符(file descriptor FD 整型), 可以用在如os模块的read方法等一些底层操作上。
 
4 
file.isatty()

如果文件连接到一个终端设备返回 True，否则返回 False。
 
5 
file.next()

返回文件下一行。
 
6 
file.read([size])

从文件读取指定的字节数，如果未给定或为负则读取所有。
 
7 
file.readline([size])

读取整行，包括 "\n" 字符。
 
8 
file.readlines([sizeint])

读取所有行并返回列表，若给定sizeint>0，返回总和大约为sizeint字节的行, 实际读取值可能比 sizeint 较大, 因为需要填充缓冲区。
 
9 
file.seek(offset[, whence])

设置文件当前位置
 
10 
file.tell()

返回文件当前位置。
 
11 
file.truncate([size])

从文件的首行首字符开始截断，截断文件为 size 个字符，无 size 表示从当前位置截断；截断之后 V 后面的所有字符被删除，其中 Widnows 系统下的换行代表2个字符大小。 
 
12 
file.write(str)

将字符串写入文件，没有返回值。
 
13 
file.writelines(sequence)

向文件写入一个序列字符串列表，如果需要换行则要自己加入每行的换行符。
 


### 练习1 

要以读文件的模式打开一个文件对象，使用Python内置的open()函数，传入文件名和标示符。

open()函数使用方式如下：

open('file名','r')


分析以下三个小题目：

以下建立文本文件file1，内容为：
 
1 一张褪色的照片，

2 好像带给我一点点怀念。

3 巷尾老爷爷卖的热汤面，

4 味道弥漫过旧旧的后院；

5 流浪猫睡熟在摇晃秋千，

6 夕阳照了一遍他咪着眼；

7 那张同桌寄的明信片，

8 安静的躺在课桌的里面。
 
根据注释，熟悉几个读文件的函数的使用方法：


#### 练习1.1 

请打开file1 文件，并逐字符读取所有文件内容并输出，然后关闭文件file1:

In [ ]:
#please input your code here
f = open('file1','r')
f_read =             #read是逐字符地读取,read可以指定参数，设定需要读取多少字符，无论一个英文字母还是一个汉字都是一个字符。


f.close()           #调用close()方法关闭文件，文件使用完毕后必须关闭，否则占用操作系统资源。



#### 练习1.2

请打开file1 文件，并读取文件第一行内容并输出，然后关闭文件file1:


In [ ]:
#please input your code here
f = open('file1','r')
                   #readline只能读取第一行代码，原理是读取到第一个换行符就停止。

                   #调用close()方法关闭文件，文件使用完毕后必须关闭，否则占用操作系统资源。


#### 练习1.3

请打开file1 文件，并读取所有行并以列表形式输出，然后关闭文件file1:


In [ ]:
#please input your code here 
f = open('file1','r')
                  #readlines会把内容以列表的形式输出。

                  #调用close()方法关闭文件，文件使用完毕后必须关闭，否则占用操作系统资源。
 

## 2 os模块的使用

如果我们要操作文件、目录，可以在命令行下面输入操作系统提供的各种命令来完成。比如dir、cp等命令。

如果要在Python程序中执行这些目录和文件的操作怎么办？其实操作系统提供的命令只是简单地调用了操作系统提供的接口函数，Python内置的os模块也
可以直接调用操作系统提供的接口函数。

使用前需要导入os模块，导入的方法是:

import os
    


### os模块使用示例


取得当前目录s = os.getcwd()   #s中保存的是当前目录(即文件夹)  

比如运行abc.py，那么输入该命令就会返回abc所在的文件夹位置。

举个简单例子，我们将abc.py放入A文件夹，并且希望不管将A文件夹放在硬盘的哪个位置，都可以在A文件夹内生成一个新文件夹，且文件夹的名字根据时间
自动生成，代码如下：

import os

import time

folder = time.strftime(r"%Y-%m-%d_%H-%M-%S",time.localtime())

os.makedirs(r'%s/%s'%(os.getcwd(),folder))



### 练习2：

已知 os.chdir(path) 方法用于改变当前工作目录到指定的路径。path 指要切换到的新路径。

如 os.chdir( "C:\\123")      #将当前目录设为"C:\123", 
请注意一点：
 
            #说明：当指定的目录不存在时，引发异常。
            #异常类型： WindowsError，系统找不到指定的文件

请先获取当前目录，并尝试更改操作，切换到"/tmp"，观察执行结果：


In [ ]:
import os, sys

path = "/tmp"

# 查看当前工作目录
#please input your code here



# 修改当前工作目录
  
    

# 查看修改后的工作目录





### 练习3：


将一个路径名分解为目录名和文件名两部分 fpath , fname = os.path.split( "你要分解的路径")

 
请拟定一个包含在二级目录的文件test.txt，其完整路径为c:\\123\\456\\test.txt，并实现将其路径名分解为目录名和文件名两部分的操作：

In [5]:
#分解 c:\123\456\test.txt
#please input your code here



a, b = 
print ()
print ()

c:\123\456
test.txt


### 练习4：

分解文件名的扩展名 fpathandname , fext = os.path.splitext( "你要分解的路径")


请拟定一个包含在二级目录的文件test.txt，其完整路径为c:\\123\\456\\test.txt，并实现将其路径名分解为文件名和扩展名两部分的操作：

In [8]:
#分解 c:\123\456\test.txt
#please input your code here



a, b = 
print ( )
print ( )

c:\123\456\test
.txt


### 练习5：

判断一个路径（目录或文件）是否存在  b = os.path.exists( "你要判断的路径")
若要判断的路径存在，则b的值为 True ,否则b的值为 Flase 。


请拟定路径如c:\\123\\456\\test.txt样式，并实现判断拟定的路径是否存在的操作：


In [7]:
#please input your code here




a = 
b = 
print 
print 

False
True


# 练习6：

判断一个路径是否是文件  b = os.path.isfile( "你要判断的路径")

判断一个路径是否是目录  b = os.path.isdir( "你要判断的路径")

根据判断结果正确与否，分别返回True 和 Flase。


请分别拟定路径c:\windows与c:\123\456\test.txt，并分别实现判断路径是否是文件或目录的操作：


In [5]:
#please input your code here





a = 
b = 
c = 
d = 

print ()

False False False True


# 练习7：

获取某目录中的文件及子目录的列表  

L = os.listdir( "你要判断的路径")


请实现获取C 盘根目录下文件及子目录列表：


In [9]:
#获取C 盘根目录下文件及子目录列表
#please input your code here




['$Recycle.Bin', '$Windows.~WS', '8d54886ad089b3275da45b6a6587c777', 'Documents and Settings', 'hiberfil.sys', 'Intel', 'MiFlashvcom.ini', 'pagefile.sys', 'PerfLogs', 'Program Files', 'Program Files (x86)', 'ProgramData', 'Recovery', 'swapfile.sys', 'System Volume Information', 'Users', 'Windows', 'XiaoMi', 'XMPCache', '迅雷下载']


# 练习8

创建子目录：

os.makedirs( path )    # path 是"要创建的子目录"

请尝试创建一个二级子目录"d:\\123\\456\\789"。


In [26]:
#创建一个二级子目录"d:\123\456\789
#please input your code here





注：

创建子目录可能失败，原因分别是：

(1) path 已存在时(不管是文件还是文件夹)

(2) 驱动器不存在

(3) 磁盘已满

(4)磁盘是只读的或没有写权限


# 练习9

删除子目录：

os.rmdir( path ) # path: "要删除的子目录"

请尝试删除练习8中创建的子目录全部删掉。


In [25]:
#please input your code here

os.rmdir( "d:\\123\\456\\789") #若执行 os.rmdir( "d:\\123\\456\\789")，发现只删除了789文件夹。
os.rmdir( "d:    )
os.rmdir( "d:    ) 
         

注：

产生异常的可能原因:
(1) path 不存在
(2) path 子目录中有文件或下级子目录
(3) 没有操作权限或只读


# 练习10

文件改名
os.rename( oldfileName, newFilename)

请先执行练习8，将练习8中创建的文件夹名:"d:\\123"改名为"d:\\321"。

In [28]:
#please input your code here       
    


# 测试题1

编程，请输入一个文件路径名或文件名如：c:\\123\\456\\test.txt，查看该文件是否存在，

如存在，打开文件并在屏幕上输出该文件内容；

如不存在，显示“输入的文件未找到！”并要求重新输入；

如文件存在但在读文件过程中发生异常，则显示“文件无法正常读出！”并要求重新输入。

（提示：请使用异常处理。“文件未找到”对应的异常名为：FileNotFoundError，其他异常直接用except匹配）


In [ ]:
#please input your code here









参考文献：

1.http://www.runoob.com/python3/python3-tutorial.html      python菜鸟教程
2.https://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000    廖雪峰python教程
3.https://wenku.baidu.com/view/e98d3ea3ad02de80d5d840be.html     python文件与文件夹的操作
4.https://wenku.baidu.com/view/7da2ddb384254b35effd340b.html?from=search      python习题选编